# Generated by Django 3.2 on 2021-04-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='newincident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Coroprate Headoffice', 'Coroprate Headoffice'), ('Operations Department', 'Operations Department'), ('Wrok Station', 'Wrok Station'), ('Marketing Division', 'Marketing Division')], max_length=45, verbose_name='Location')),
                ('incident_department', models.TextField(verbose_name='Incident Department :')),
                ('date_incident', models.DateTimeField(verbose_name='Date and Time of Incident')),
                ('incident_location', models.TextField(verbose_name='Incident Location')),
                ('initial_serverity', models.TextField(choices=[('Mild', 'Mild'), ('Modarate', 'Modarate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], max_length=55)),
                ('action_tacken', models.TextField(verbose_name='Immediate Action Taken :')),
                ('sub_type', models.CharField(choices=[('Enviourmental Incident', 'Enviourmental Incident'), ('Injury/illness', 'Injury/illness'), ('Property Demage', 'Property Demage'), ('Vehicle', 'Vehicle')], max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
